repos:
  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        language: system
        entry: mise exec -- gofmt -w
        types: [go]
        pass_filenames: true

      - id: go-vet
        name: go vet
        language: system
        entry: mise exec -- go vet ./...
        types: [go]
        pass_filenames: false
